<Project>
  <!-- https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management -->
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Autofac" Version="9.3.1" />
    <PackageVersion Include="AutoMapper" Version="16.2.0" />
    <PackageVersion Include="NLog" Version="6.1.4" />
    <!-- Avalonia -->
    <PackageVersion Include="Avalonia" Version="12.1.0" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.1.0" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>
</Project>