global using System;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using Autofac;
global using Gguc.Aoc.ConsoleApp.DependencyModules;
global using Gguc.Aoc.Core.Logging;
global using Gguc.Aoc.Core.Services;
global using Gguc.Aoc.Core.Utils;
global using Gguc.Aoc.Hub.DependencyModules;
